name: train
checkpoint_iteration: 500
summary_iteration: 1
no_summary_images: False
logging_iteration: 1
optimizer:
  learning_rate: 0.0003
  name: adam
  loss_balance_scheme: light
  gradient_accumulation: 1
