name: uresnet
bias: True
batch_norm: True
n_initial_filters: 16
blocks_per_layer: 2
blocks_deepest_layer: 5
blocks_final: 5
network_depth: 6
filter_size_deepest: 5
bottleneck_deepest: 256
residual: True
block_concat: False
growth_rate: 1
conv_mode: 2D
downsampling: max_pooling
upsampling: interpolation
connections: concat
data_format: ${data.data_format}
weight_decay: 0.0
